development: &development
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: fanrank_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  database: fanrank_test
  <<: *development

cucumber:
  <<: *test
